### ISSUE TITLE
RunTasksAutomatically, if Tasks kills DB somehow it can't recover!

### ISSUE THREAD

**Issue by jarofgreen** [OpenACalendar/OpenACalendar-Web-Core#380]
```  
EXCEPTION SQLSTATE[22007]: Invalid datetime format: 7 ERROR:  invalid input syntax for type date: "1959"
        Finished 2015-04-15 07:07:02
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block' in /meetyournextmp-web/core/php/BaseTask.php:106
Stack trace:
#0 /meetyournextmp-web/core/php/BaseTask.php(106): PDOStatement->execute(Array)
#1 /meetyournextmp-web/core/cli/runTasksAutomatically.php(29): BaseTask->runAutomaticallyNowIfShould(true)
#2 {main}
  thrown in /meetyournextmp-web/core/php/BaseTask.php on line 106
```

**Comment by jarofgreen** [comment]
So, if there is an Exception, we'll just stop running any further tasks. Hard to recover DB, especially if other DB's involved later, and they should not crash anyway!

If Exception, we don't try again for 24 hours - to prevent a task that exceptions from stopping others running?

If Exception, alert sysadmin user via email/notification?

**Comment by jarofgreen** [comment]
see #325

**Comment by jarofgreen** [comment]
>  If Exception, alert sysadmin user via email/notification? 

Write to MonoLog - other tools can pick up from there

**Comment by jarofgreen** [comment]
> If Exception, we don't try again for 24 hours - to prevent a task that exceptions from stopping others running?

Come back to this later with real data. An Exception should be the last thing that happens.
